name: CI

on:
  push:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  # build allways
  build:
    name: Build allways and publish on release or rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build (allways) and push (on release or rebuild)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ (github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags')) || github.event_name == 'release' }}
          # Pull and no-cache ensure that a rebuild uses the latest base image
          # and that apt-get update/upgrade are run again
          pull: ${{ github.event_name == 'workflow_dispatch' }}
          no-cache: ${{ github.event_name == 'workflow_dispatch' }}
          tags: daschswiss/nginx-server:latest, daschswiss/nginx-server:${{ steps.get_version.outputs.VERSION }}${{ (github.event_name == 'workflow_dispatch' && format('-{0}', github.run_number)) || '' }}
